
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import './globals.css';
import { AuthProvider } from "@/context/AuthContext";
import ProtectedRoute from "@/components/ProtectedRoute";
import LayoutClient from "@/components/Layoutclient";
import { CartProvider } from "./cart/CartContext";


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "sakroob",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans`}>
        <AuthProvider>
          <CartProvider>
            <ProtectedRoute>
              <LayoutClient>
                {children}
              </LayoutClient>
            </ProtectedRoute>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}



